package com.skylinetrailcomputing.semaphore

import com.skylinetrailcomputing.semaphore.core.KeypointContract
import com.skylinetrailcomputing.semaphore.core.Mode
import com.skylinetrailcomputing.semaphore.core.SharedFiles
import com.skylinetrailcomputing.semaphore.core.TestVectors
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Test

/**
 * Cross-platform parity harness (Issue #14, Epic 2).
 *
 * Runs every vector in `shared/test_vectors.json` through the full
 * feature-extraction -> classification -> decode path and asserts the emitted
 * string and white-box position ids match the fixtures exactly. The Swift
 * `ParityTests` asserts against the same file, so green on both platforms is
 * the byte-for-byte *parity* guarantee (spec §6).
 *
 * Parity, not conformance: the fixtures are generated by the reference decoder
 * these ports mirror, so this proves the two platforms agree with each other
 * and with that reference -- not that the reference is itself correct.
 * Conformance to real semaphore rests on the independently chart-verified
 * alphabet (Epic 1, `shared/ALPHABET-VERIFICATION.md`).
 *
 * Scope is downstream of the adapter: these vectors are the adapter's *output*
 * (post-mirror, post-y-flip, normalized, y-up, signer's perspective), so this
 * harness does not exercise the flips (Epic 3 native fixtures) or temporal
 * smoothing/commit timing (Epic 4).
 */
class ParityTest {
    @Test
    fun singlePoseVectors() {
        val decoder = referenceDecoder()
        val vectors = SharedFiles.load<TestVectors>("test_vectors.json")
        assertFalse("no single-pose vectors loaded", vectors.singlePoseVectors.isEmpty())

        for (vector in vectors.singlePoseVectors) {
            val mode = Mode.valueOf(vector.modeBefore)
            val result = decoder.decodeFrame(keypointsFrom(vector.keypoints), mode)
            assertEquals("emit mismatch for ${vector.name}", vector.expected, result.emit)
            assertEquals(
                "position ids mismatch for ${vector.name}",
                vector.expectedPositionIds,
                result.ids,
            )
        }
    }

    @Test
    fun sequenceVectors() {
        val decoder = referenceDecoder()
        val vectors = SharedFiles.load<TestVectors>("test_vectors.json")
        assertFalse("no sequence vectors loaded", vectors.sequenceVectors.isEmpty())

        for (sequence in vectors.sequenceVectors) {
            var mode = Mode.valueOf(sequence.modeStart)
            for (frame in sequence.frames) {
                val result = decoder.decodeFrame(keypointsFrom(frame.keypoints), mode)
                val label = "${sequence.name}/${frame.name}"
                assertEquals("emit mismatch for $label", frame.expected, result.emit)
                assertEquals(
                    "position ids mismatch for $label",
                    frame.expectedPositionIds,
                    result.ids,
                )
                mode = result.mode // thread decoder mode through the sequence
            }
        }
    }

    /**
     * `flatten()` is the input-side analogue of `label_order`: it is the only
     * thing that exercises the 12-float model input until the Epic-5 classifier
     * lands, so pin its order to the frozen contract now. Sentinel values are
     * distinct per (keypoint, component) so any transposition in `flatten()` --
     * or drift from `model_input_order.floats` -- is caught.
     */
    @Test
    fun flattenMatchesModelInputOrder() {
        val contract = SharedFiles.load<KeypointContract>("keypoint_contract.json")
        val names =
            listOf(
                "left_shoulder", "left_elbow", "left_wrist",
                "right_shoulder", "right_elbow", "right_wrist",
            )
        // x, y, confidence per keypoint -- all distinct across the whole vector.
        val map = names.mapIndexed { i, name -> name to listOf(i * 3.0, i * 3.0 + 1, i * 3.0 + 2) }.toMap()

        val flat = keypointsFrom(map).flatten()
        assertEquals("flatten() length", contract.modelInputOrder.length, flat.size)
        assertEquals(
            "contract floats vs declared length",
            contract.modelInputOrder.length,
            contract.modelInputOrder.floats.size,
        )

        contract.modelInputOrder.floats.forEachIndexed { i, spec ->
            val (name, comp) = spec.split(".") // e.g. "left_shoulder.x"
            val triple = requireNotNull(map[name]) { "unknown keypoint $name in $spec" }
            val expected =
                when (comp) {
                    "x" -> triple[0]
                    "y" -> triple[1]
                    else -> error("model_input_order has a non-x/y component: $spec")
                }
            assertEquals("flatten()[$i] != model_input_order $spec", expected, flat[i], 0.0)
        }
    }
}
