import XCTest

@testable import SemaphoreTranslator

/// Cross-platform parity harness (Issue #14, Epic 2).
///
/// Runs every vector in `shared/test_vectors.json` through the full
/// feature-extraction → classification → decode path and asserts the emitted
/// string and white-box position ids match the fixtures exactly. The Kotlin
/// `ParityTest` asserts against the same file, so green on both platforms is
/// the byte-for-byte *parity* guarantee (spec §6).
///
/// Parity, not conformance: the fixtures are generated by the reference decoder
/// these ports mirror, so this proves the two platforms agree with each other
/// and with that reference — not that the reference is itself correct.
/// Conformance to real semaphore rests on the independently chart-verified
/// alphabet (Epic 1, `shared/ALPHABET-VERIFICATION.md`).
///
/// Scope is downstream of the adapter: these vectors are the adapter's *output*
/// (post-mirror, post-y-flip, normalized, y-up, signer's perspective), so this
/// harness does not exercise the flips (Epic 3 native fixtures) or temporal
/// smoothing/commit timing (Epic 4).
final class ParityTests: XCTestCase {
    func testSinglePoseVectors() throws {
        let decoder = try ReferenceDecoder.make()
        let vectors = try SharedFiles.load(TestVectors.self, "test_vectors.json")
        XCTAssertFalse(vectors.singlePoseVectors.isEmpty, "no single-pose vectors loaded")

        for vector in vectors.singlePoseVectors {
            let mode = try XCTUnwrap(Mode(rawValue: vector.modeBefore), "bad mode in \(vector.name)")
            let kp = try makeKeypoints(from: vector.keypoints, vector.name)
            let result = decoder.decodeFrame(kp, mode: mode)
            XCTAssertEqual(result.emit, vector.expected, "emit mismatch for \(vector.name)")
            XCTAssertEqual(
                result.ids, vector.expectedPositionIds, "position ids mismatch for \(vector.name)")
        }
    }

    func testSequenceVectors() throws {
        let decoder = try ReferenceDecoder.make()
        let vectors = try SharedFiles.load(TestVectors.self, "test_vectors.json")
        XCTAssertFalse(vectors.sequenceVectors.isEmpty, "no sequence vectors loaded")

        for sequence in vectors.sequenceVectors {
            var mode = try XCTUnwrap(
                Mode(rawValue: sequence.modeStart), "bad mode_start in \(sequence.name)")
            for frame in sequence.frames {
                let label = "\(sequence.name)/\(frame.name)"
                let kp = try makeKeypoints(from: frame.keypoints, label)
                let result = decoder.decodeFrame(kp, mode: mode)
                XCTAssertEqual(result.emit, frame.expected, "emit mismatch for \(label)")
                XCTAssertEqual(
                    result.ids, frame.expectedPositionIds, "position ids mismatch for \(label)")
                mode = result.mode  // thread decoder mode through the sequence
            }
        }
    }

    /// `flatten()` is the input-side analogue of `label_order`: it is the only
    /// thing that exercises the 12-float model input until the Epic-5 classifier
    /// lands, so pin its order to the frozen contract now. Sentinel values are
    /// distinct per (keypoint, component) so any transposition in `flatten()` —
    /// or drift from `model_input_order.floats` — is caught.
    func testFlattenMatchesModelInputOrder() throws {
        let contract = try SharedFiles.load(KeypointContract.self, "keypoint_contract.json")
        let names = [
            "left_shoulder", "left_elbow", "left_wrist",
            "right_shoulder", "right_elbow", "right_wrist",
        ]
        var map: [String: [Double]] = [:]
        for (i, name) in names.enumerated() {
            let base = Double(i) * 3
            map[name] = [base, base + 1, base + 2]  // x, y, confidence — all distinct
        }

        let flat = try makeKeypoints(from: map, "flatten contract").flatten()
        XCTAssertEqual(flat.count, contract.modelInputOrder.length, "flatten() length")
        XCTAssertEqual(
            contract.modelInputOrder.floats.count, contract.modelInputOrder.length,
            "contract floats vs declared length")

        for (i, spec) in contract.modelInputOrder.floats.enumerated() {
            let parts = spec.split(separator: ".")  // e.g. "left_shoulder.x"
            let name = String(parts[0])
            let triple = try XCTUnwrap(map[name], "unknown keypoint \(name) in \(spec)")
            let expected: Double
            switch parts.last {
            case "x": expected = triple[0]
            case "y": expected = triple[1]
            default:
                XCTFail("model_input_order has a non-x/y component: \(spec)")
                continue
            }
            XCTAssertEqual(flat[i], expected, "flatten()[\(i)] != model_input_order \(spec)")
        }
    }
}
